//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parkmania.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beach
    {
        public Nullable<int> id { get; set; }
        public string name { get; set; }
        public string Phone { get; set; }
        public string County { get; set; }
        public Nullable<double> EntranceFee { get; set; }
        public Nullable<double> PermitRequired { get; set; }
        public string UnitDescription { get; set; }
        public Nullable<double> TotalNumofSites { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public int Bid { get; set; }
    }
}
