//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parkmania.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Park
    {
        public string Park_Name { get; set; }
        public string Park_Type { get; set; }
        public Nullable<double> Zip_Code { get; set; }
        public Nullable<double> Aqua_Feat__Pool { get; set; }
        public string Aqua_Feat__Spray { get; set; }
        public string Backstop__Practice { get; set; }
        public Nullable<double> Ballfield { get; set; }
        public Nullable<double> Basketball { get; set; }
        public string Blueway { get; set; }
        public string Complex__Ballfield { get; set; }
        public string Complex__Tennis { get; set; }
        public string Concessions { get; set; }
        public string Disk_Golf { get; set; }
        public string Driving_Range { get; set; }
        public Nullable<double> Educational_Experience { get; set; }
        public Nullable<double> Event_Space { get; set; }
        public string Fitness_Course { get; set; }
        public Nullable<double> Garden__Community { get; set; }
        public Nullable<double> Garden__Display { get; set; }
        public string Golf { get; set; }
        public string Hockey__Ice { get; set; }
        public Nullable<double> Loop_Walk { get; set; }
        public Nullable<double> MP_Field__Large { get; set; }
        public string MP_Field__Multiple { get; set; }
        public string MP_Field__Small { get; set; }
        public string Multiuse_Court { get; set; }
        public string Natural_Area { get; set; }
        public Nullable<double> Open_Turf { get; set; }
        public Nullable<double> Open_Water { get; set; }
        public string Other___Active { get; set; }
        public string Other_Passive { get; set; }
        public Nullable<double> Passive_Node { get; set; }
        public Nullable<double> Picnic_Grounds { get; set; }
        public Nullable<double> Playground__Destination { get; set; }
        public Nullable<double> Playground__Local { get; set; }
        public Nullable<double> Public_Art { get; set; }
        public string Shelter { get; set; }
        public Nullable<double> Shelter__Group { get; set; }
        public string Skate_Park { get; set; }
        public string Sledding_Hill { get; set; }
        public Nullable<double> Structure { get; set; }
        public string Tennis { get; set; }
        public string Trail__Primitive { get; set; }
        public string Volleyball { get; set; }
        public Nullable<double> Water_Access__Developed { get; set; }
        public Nullable<double> Water_Access__General { get; set; }
        public Nullable<double> Water_Feature { get; set; }
        public string Location_1 { get; set; }
        public Nullable<int> FID { get; set; }
        public int ID { get; set; }
    }
}
